# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f53a5a9423006b812c36ee29183ba939da9fc3d1e8d8781664c925ab6e61281662f76ffadc44cdc965d9a48b6173f13b53cb72559f25906788f442a050bcd63
  facebook_app_id: 1713772155579412
  facebook_app_secret: fd6a05caf29b4047975a74691a19ca8d
  mailer_username: mikaelkessler@gmail.com
  mailer_password: gggahiaqjfreslkb
  redis_url: redis://localhost:6379/0/
  twitter_consumer_key: 11Sh4IV9q6L3QF4If92arXXsM
  twitter_consumer_secret: hoPj2ydh37s7760FidCGNCmDk5Q7cUannRtuTVcABMKC5Ql4hN
  twitter_access_token: 109068078-R6TAe82T7ZT3pkaK5x9vxgaJizIMjeSKfxdqZQDP
  twitter_access_token_secret: 4fZ140W0lLjxsDqyCQWbYgKYdMj30DEHqZzD8t6A263wx

test:
  secret_key_base: e166cb10b68a78f009ab9f038c18715cdb4d659c18b858e75daeb99e41c739fdd6e605bdbb8d1acea111a61efa13488ea6d5abbb56258fef0fc198dc8eb491b6
  facebook_app_id: 1713772155579412
  facebook_app_secret: fd6a05caf29b4047975a74691a19ca8d
  redis_url: redis://localhost:6379/0/
  twitter_consumer_key: 11Sh4IV9q6L3QF4If92arXXsM
  twitter_consumer_secret: hoPj2ydh37s7760FidCGNCmDk5Q7cUannRtuTVcABMKC5Ql4hN
  twitter_access_token: 109068078-R6TAe82T7ZT3pkaK5x9vxgaJizIMjeSKfxdqZQDP
  twitter_access_token_secret: 4fZ140W0lLjxsDqyCQWbYgKYdMj30DEHqZzD8t6A263wx

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  redis_url: <%= ENV["REDISTOGO_URL"] %>
